# https://circleci.com/docs/2.0/language-javascript/
version: 2
defaults: &defaults
  working_directory: ~/rep
  docker:
    - image: circleci/node:latest

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Setup Git
          command: git config --global user.name dsfx3d && git config --global user.email dsfx3d@gmail.com
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: ['.']
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Send Coverage Report
          command: npm run cov:send && npm run cov:check
      - persist_to_workspace:
          root: ~/repo
          paths: ['.']

  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

      - run:
          name: Prepare Release
          command: npm run prepare-release
      - run:
          name: Publish
          command: npm publish


workflows:
  version: 2
  test-release:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - release:
          requires:
            - test
