# https://circleci.com/docs/2.0/language-javascript/
version: 2
jobs:
  'node-latest':
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run prepare-release
      - run: npm test
      - run: npm run cov:send
      - run: npm run cov:check
      - run: npm publish

workflows:
  version: 2
  build:
    jobs:
      - 'node-latest'
